language: node_js
node_js:
  - "stable"
env:
  global:
    - GH_REF: "github.com/APIs-guru/api-models.git"
deploy:
  provider: script
  script: ./scripts/deploy_gh_pages.sh 2>&1 | sed "s/${GH_TOKEN}/xxPASSxx/"
  on:
    branch: master
