swagger: "2.0"
info:
  version: "2.0"
  title: "APIs.guru"
  description: "Wikipedia for Web APIs. Repository of API specs in OpenAPI(fka Swagger) 2.0 format."
  contact:
    name: "APIs.guru"
    url: http://APIs.guru
    email: "founders@apis.guru"
  license:
    name: "CC0 1.0"
    url: "https://github.com/APIs-guru/api-models#licenses"
  x-logo:
    url: https://apis.guru/branding/logo_vertical.svg
externalDocs:
  url: https://github.com/APIs-guru/api-models/blob/master/API.md
produces:
  - application/json
security: []
paths:
  /list.json:
    get:
     operationId: listAPIs
     summary: List all APIs in collection
     responses:
      200:
        description: OK
        schema:
          $ref: "#/definitions/APIs"
  /metrics.json:
    get:
     operationId: listMetrics
     summary: List of some basic metrics for entire collection
     responses:
      200:
        description: OK
        schema:
          $ref: "#/definitions/Metrics"
definitions:
  APIs:
    description: |
      List of API details.
      It consist of JSON object with API IDs(`<provider>[:<service>]`) as keys.
    type: object
    additionalProperties:
      $ref: "#/definitions/API"
    minProperties: 1
    example:
      'googleapis.com:drive':
        added: '2015-02-22T20:00:45.000Z'
        preferred: v3
        versions:
          v2:
            added: '2015-02-22T20:00:45.000Z'
            info:
              title: Drive
              version: v2
              x-apiClientRegistration:
                url: 'https://console.developers.google.com'
              x-logo:
                url: https://api.apis.guru/v2/cache/logo/https_www.gstatic.com_images_icons_material_product_2x_drive_32dp.png
              x-origin:
                format: google
                url: 'https://www.googleapis.com/discovery/v1/apis/drive/v2/rest'
                version: v1
              x-preferred: false
              x-providerName: googleapis.com
              x-serviceName: drive
            swaggerUrl: 'https://api.apis.guru/v2/specs/googleapis.com/drive/v2/swagger.json'
            swaggerYamlUrl: 'https://api.apis.guru/v2/specs/googleapis.com/drive/v2/swagger.yaml'
            updated: '2016-06-17T00:21:44.000Z'
          v3:
            added: '2015-12-12T00:25:13.000Z'
            info:
              title: Drive
              version: v3
              x-apiClientRegistration:
                url: 'https://console.developers.google.com'
              x-logo:
                url: https://api.apis.guru/v2/cache/logo/https_www.gstatic.com_images_icons_material_product_2x_drive_32dp.png
              x-origin:
                format: google
                url: 'https://www.googleapis.com/discovery/v1/apis/drive/v3/rest'
                version: v1
              x-preferred: true
              x-providerName: googleapis.com
              x-serviceName: drive
            swaggerUrl: 'https://api.apis.guru/v2/specs/googleapis.com/drive/v3/swagger.json'
            swaggerYamlUrl: 'https://api.apis.guru/v2/specs/googleapis.com/drive/v3/swagger.yaml'
            updated: '2016-06-17T00:21:44.000Z'
  API:
    description: Meta information about API
    type: object
    required:
      - added
      - preferred
      - versions
    properties:
      added:
        description: Timestamp when this API was first added to collection
        type: string
        format: date-time
      preferred:
        description: Recommended version
        type: string
      versions:
        description: List supported versions of API
        type: object
        additionalProperties:
          $ref: "#/definitions/ApiVersion"
        minProperties: 1
    additionalProperties: false
  ApiVersion:
    type: object
    required:
      - added
      - updated
      - swaggerUrl
      - swaggerYamlUrl
      - info
    properties:
      added:
        description: Timestamp when this version was added
        type: string
        format: date-time
      updated:
        description: Timestamp when this version was updated
        type: string
        format: date-time
      swaggerUrl:
        description: URL of Swagger spec in JSON format
        type: string
        format: url
      swaggerYamlUrl:
        description: URL of Swagger spec in YAML format
        type: string
        format: url
      info:
        description: Copy of `info` section from Swagger spec
        type: object
        minProperties: 1
    additionalProperties: false
  Metrics:
    description: List of some basic metrics for entire collection
    type: object
    required:
      - numSpecs
      - numAPIs
      - numEndpoints
    properties:
      numSpecs:
        description: Number of APIs specification including different versions of the same API
        type: integer
        minimum: 1
      numAPIs:
        description: Number of APIs
        type: integer
        minimum: 1
      numEndpoints:
        description: Total number of endpoints inside all specifications
        type: integer
        minimum: 1
    additionalProperties: false
    example:
      numAPIs: 238
      numEndpoints: 6448
      numSpecs: 302
